import 'package:flutter/material.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedFesearchWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedVectorWidget11.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedIconWidget3.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedIconWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedIconWidget2.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedSidebarWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedHOMEWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedVectorWidget14.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedIconWidget1.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedVOUCHERAPPWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedVectorWidget13.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedAntdesignsearchoutlinedWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel21widget/generated/GeneratedGroupWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Google Pixel 2 - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel21Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 32.0,
                child: GeneratedVOUCHERAPPWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 35.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 51.0,
                child: GeneratedSidebarWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 32.0,
                child: GeneratedHOMEWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 400.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 170.0,
                child: GeneratedIconWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 170.0,
                child: GeneratedIconWidget1(),
              ),
              Positioned(
                left: 35.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 170.0,
                child: GeneratedIconWidget2(),
              ),
              Positioned(
                left: 230.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 170.0,
                child: GeneratedIconWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.17487964490904426;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 71.87553405761719;

                  double percentHeight = 0.03847469220246238;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 28.125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6155717761557178,
                        translateY: constraints.maxHeight * 0.38799589603283174,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget11())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.17487834549878345;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 71.875;

                  double percentHeight = 0.04600664757181942;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 33.630859375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6155717761557178,
                        translateY: constraints.maxHeight * 0.34097127222982215,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget12())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.13686131386861314;
                  double scaleX = (constraints.maxWidth * percentWidth) / 56.25;

                  double percentHeight = 0.1282623332763338;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 93.759765625;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7068126520681265,
                        translateY: constraints.maxHeight * 0.2982216142270862,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget13())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.20275750821524294;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 83.33333587646484;

                  double percentHeight = 0.10829913012795507;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      79.16666412353516;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.15328467153284672,
                        translateY: constraints.maxHeight * 0.573187414500684,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget14())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.24330900243309003;

                  final double height =
                      constraints.maxHeight * 0.13679890560875513;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6082725060827251,
                        y: constraints.maxHeight * 0.5581395348837209,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -407.0,
                top: -14.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedAntdesignsearchoutlinedWidget(),
              ),
              Positioned(
                left: 355.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFesearchWidget(),
              )
            ]),
      ),
    ));
  }
}
