import 'package:flutter/material.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel23widget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel23widget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel23widget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel23widget/generated/GeneratedACCOUNTWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel23widget/generated/GeneratedSidebarWidget2.dart';

/* Frame Google Pixel 2 - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 51.0,
                child: GeneratedSidebarWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 50.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 35.0,
                child: GeneratedACCOUNTWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 50.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 360.0,
                child: GeneratedGroup6Widget(),
              )
            ]),
      ),
    ));
  }
}
