import 'package:flutter/material.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel22widget/generated/GeneratedPilihanWidget.dart';

/* Frame Google Pixel 2 - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel22Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 708.0,
                child: GeneratedPilihanWidget(),
              )
            ]),
      ),
    ));
  }
}
