import 'package:flutter/material.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedForgetPasswordWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedHavenotaccountyetWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedJamtwittersquareWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedEiscinstagramWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedIcbaselineaccountboxWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedTypeyourusernameWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedTypeyourpasswordWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedVectorWidget23.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedBxbxlockWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedLOGINWidget1.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedOrSignUpUsingWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel24widget/generated/GeneratedDashiconsfacebookWidget.dart';

/* Frame Google Pixel 2 - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel24Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 170.0,
                top: 60.0,
                right: 166.0,
                bottom: 638.0,
                width: null,
                height: null,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 120.0,
                right: 274.0,
                bottom: 585.0,
                width: null,
                height: null,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 89.0,
                top: 155.0,
                right: 158.0,
                bottom: 553.0,
                width: null,
                height: null,
                child: GeneratedTypeyourusernameWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 255.0,
                right: 158.0,
                bottom: 453.0,
                width: null,
                height: null,
                child: GeneratedTypeyourpasswordWidget(),
              ),
              Positioned(
                left: 218.0,
                top: 325.0,
                right: 47.0,
                bottom: 383.0,
                width: null,
                height: null,
                child: GeneratedForgetPasswordWidget(),
              ),
              Positioned(
                left: 143.0,
                top: 473.0,
                right: 131.0,
                bottom: 235.0,
                width: null,
                height: null,
                child: GeneratedOrSignUpUsingWidget(),
              ),
              Positioned(
                left: 119.0,
                top: 623.0,
                right: 108.0,
                bottom: 85.0,
                width: null,
                height: null,
                child: GeneratedHavenotaccountyetWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 220.0,
                right: 276.0,
                bottom: 485.0,
                width: null,
                height: null,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 90.99832153320312;
                  final double scaleX =
                      width <= 0 ? 0 : (width / 320.0016784667969);

                  final double height = constraints.maxHeight - 730.0;
                  final double scaleY = height <= 0 ? 0 : (height / 1.0);

                  final Widget child = GeneratedLine1Widget();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(
                          scaleX,
                          0,
                          0,
                          0,
                          0,
                          scaleY,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          50.0 * scaleX,
                          196.98504638671875 * scaleY,
                          0,
                          1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 90.99832153320312;
                  final double scaleX =
                      width <= 0 ? 0 : (width / 320.0016784667969);

                  final double height = constraints.maxHeight - 730.0;
                  final double scaleY = height <= 0 ? 0 : (height / 1.0);

                  final Widget child = GeneratedLine2Widget();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0,
                          1, 0, 50.0 * scaleX, 298.0 * scaleY, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 50.0,
                top: 377.0,
                right: 41.0,
                bottom: 302.0,
                width: null,
                height: null,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 390.0,
                right: 162.0,
                bottom: 310.0,
                width: null,
                height: null,
                child: GeneratedLOGINWidget1(),
              ),
              Positioned(
                left: 170.0,
                top: 660.0,
                right: 154.0,
                bottom: 43.0,
                width: null,
                height: null,
                child: GeneratedSIGNUPWidget(),
              ),
              Positioned(
                left: 167.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedJamtwittersquareWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedDashiconsfacebookWidget(),
              ),
              Positioned(
                left: 222.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 95.0,
                child: GeneratedEiscinstagramWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedBxbxlockWidget(),
              ),
              Positioned(
                left: 236.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselineaccountboxWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06326033135110154;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      25.999996185302734;

                  double percentHeight = 0.03556771545827633;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 26.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.1338199606197014,
                        translateY: constraints.maxHeight * 0.20930232558139536,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget23())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
