import 'package:flutter/material.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel26widget/generated/GeneratedKODEWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel26widget/generated/GeneratedSidebarWidget4.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel26widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel26widget/generated/GeneratedAkariconscopyWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel26widget/generated/GeneratedDISKON20KWidget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel26widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/voucherapp/generatedgooglepixel26widget/generated/GeneratedRectangle12Widget.dart';

/* Frame Google Pixel 2 - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel26Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 683.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 51.0,
                child: GeneratedSidebarWidget4(),
              ),
              Positioned(
                left: 52.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 224.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 87.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 32.0,
                child: GeneratedKODEWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 163.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 29.0,
                child: GeneratedDISKON20KWidget(),
              ),
              Positioned(
                left: 296.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconscopyWidget(),
              )
            ]),
      ),
    ));
  }
}
